import pandas as pd
import sql 


df = sql.do("""SELECT * FROM sampled_data;
""")

df = pd.DataFrame(df, columns=[
    'AGEP 年龄',
    'COW 阶级',
    'NWAB 临时缺勤',
    'NWAV 可供工作使用',
    'NWLA 裁员',
    'NWLK 找工作中',
    'NWRE 召回',
    'OIP 其他收入',
    'PAP 救济收入',
    'SCH 学校',
    'SCHG 年级入学',
    'SCHL 教育等级',
    'SEX 性别',
    'WKL 上次工作时间',
    'WKWN 过去12个月工作时间',
    'DIS 残疾',
    'NAICSP 行业',
    'SOCP 职位'
])

naics_dict = {
    "111": "AGR-Crop Production",
    "112": "AGR-Animal Production And Aquaculture",
    "1133": "AGR-Logging",
    "113M": "AGR-Forestry Except Logging",
    "114": "AGR-Fishing, Hunting And Trapping",
    "115": "AGR-Support Activities For Agriculture And Forestry",
    "211": "EXT-Oil And Gas Extraction",
    "2121": "EXT-Coal Mining",
    "2122": "EXT-Metal Ore Mining",
    "2123": "EXT-Nonmetallic Mineral Mining And Quarrying",
    "213": "EXT-Support Activities For Mining",
    "2211P": "UTL-Electric Power Generation, Transmission And Distribution",
    "2212P": "UTL-Natural Gas Distribution",
    "22132": "UTL-Sewage Treatment Facilities",
    "2213M": "UTL-Water Supply And Irrigation Systems, And Steam And Air-conditioning Supply",
    "221MP": "UTL-Electric And Gas, And Other Combinations",
    "22S": "UTL-Not Specified Utilities",
    "23": "CON-Construction (The Cleaning Of Buildings And Dwellings Is Incidental During Construction And Immediately After Construction)",
    "3113": "MFG-Sugar And Confectionery Products",
    "3114": "MFG-Fruit And Vegetable Preserving And Specialty Food",
    "3115": "MFG-Dairy Product",
    "3116": "MFG-Animal Slaughtering And Processing",
    "311811": "MFG-Retail Bakeries",
    "3118Z": "MFG-Bakeries And Tortilla, Except Retail Bakeries",
    "311M1": "MFG-Animal Food, Grain And Oilseed Milling",
    "311M2": "MFG-Seafood And Other Miscellaneous Foods, N.E.C.",
    "311S": "MFG-Not Specified Food Industries",
    "3121": "MFG-Beverage",
    "3122": "MFG-Tobacco",
    "3131": "MFG-Fiber, Yarn, And Thread Mills",
    "3132Z": "MFG-Fabric Mills, Except Knit Fabric Mills",
    "3133": "MFG-Textile And Fabric Finishing And Fabric Coating Mills",
    "31411": "MFG-Carpet And Rug Mills",
    "314Z": "MFG-Textile Product Mills, Except Carpet And Rug",
    "315M": "MFG-Cut And Sew, And Apparel Accessories And Other Apparel",
    "3162": "MFG-Footwear",
    "316M": "MFG-Leather And Hide Tanning And Finishing, And Other Leather And Allied Product",
    "31M": "MFG-Knit Fabric Mills, And Apparel Knitting Mills",
    "3211": "MFG-Sawmills And Wood Preservation",
    "3212": "MFG-Veneer, Plywood, And Engineered Wood Product",
    "32199M": "MFG-Manufactured Home (Mobile Home) And Prefabricated Wood Building",
    "3219ZM": "MFG-Miscellaneous Wood Product",
    "3221": "MFG-Pulp, Paper, And Paperboard Mills",
    "32221": "MFG-Paperboard Container",
    "3222M": "MFG-Miscellaneous Paper And Pulp Products",
    "3231": "MFG-Printing And Related Support Activities",
    "32411": "MFG-Petroleum Refineries",
    "3241M": "MFG-Petroleum And Coal Products Manufacturing, Except Petroleum Refineries",
    "3252": "MFG-Resin, Synthetic Rubber, And Artificial And Synthetic Fibers And Filaments",
    "3253": "MFG-Pesticide, Fertilizer, And Other Agricultural Chemical",
    "3254": "MFG-Pharmaceutical And Medicine",
    "3255": "MFG-Paint, Coating, And Adhesive",
    "3256": "MFG-Soap, Cleaning Compound, And Toilet Preparation",
    "325M": "MFG-Basic Chemical, And Other Chemical Product And Preparation",
    "3261": "MFG-Plastics Product",
    "32621": "MFG-Tire",
    "3262M": "MFG-Rubber Products, Except Tires",
    "32711": "MFG-Pottery, Ceramics, And Plumbing Fixture",
    "32712": "MFG-Clay Building Material And Refractories",
    "3272": "MFG-Glass And Glass Product",
    "3279": "MFG-Other Nonmetallic Mineral Product",
    "327M": "MFG-Cement, Concrete, Lime, And Gypsum Product",
    "3313": "MFG-Alumina And Aluminum Production And Processing",
    "3314": "MFG-Nonferrous Metal (Except Aluminum) Production And Processing",
    "3315": "MFG-Foundries",
    "331M": "MFG-Iron And Steel Mills And Steel Product",
    "3321": "MFG-Forging And Stamping",
    "3322": "MFG-Cutlery And Handtool",
    "3327": "MFG-Machine Shops; Turned Product; Screw, Nut, And Bolt",
    "3328": "MFG-Coating, Engraving, Heat Treating, And Allied Activities",
    "33299M": "MFG-Ordnance",
    "332M": "MFG-Architectural And Structural Metals, And Boiler, Tank, And Shipping Container",
    "332MZ": "MFG-Miscellaneous Fabricated Metal Product",
    "33311": "MFG-Agricultural Implement",
    "3331M": "MFG-Construction, And Mining And Oil And Gas Field Machinery",
    "3333": "MFG-Commercial And Service Industry Machinery",
    "3335": "MFG-Metalworking Machinery",
    "3336": "MFG-Engine, Turbine, And Power Transmission Equipment",
    "333MS": "MFG-Machinery, N.E.C. Or Not Specified",
    "3341": "MFG-Computer And Peripheral Equipment",
    "3345": "MFG-Navigational, Measuring, Electromedical, And Control Instruments",
    "334M1": "MFG-Communications, Audio, And Video Equipment",
    "334M2": "MFG-Semiconductor, Magnetic And Optical Media, And Other Electronic Component",
    "3352": "MFG-Household Appliance",
    "335M": "MFG-Electric Lighting And Electrical Equipment, And Other Electrical Component, N.E.C.",
    "33641M1": "MFG-Aircraft, Aircraft Engine, And Aircraft Parts",
    "33641M2": "MFG-Guided Missile And Space Vehicle And Parts",
    "3365": "MFG-Railroad Rolling Stock",
    "3366": "MFG-Ship And Boat Building",
    "3369": "MFG-Other Transportation Equipment",
    "336M": "MFG-Motor Vehicles And Motor Vehicle Equipment",
    "337": "MFG-Furniture And Related Product",
    "3391": "MFG-Medical Equipment And Supplies",
    "3399M": "MFG-Sporting And Athletic Goods, And Doll, Toy And Game",
    "3399ZM": "MFG-Miscellaneous Manufacturing, N.E.C.",
    "33MS": "MFG-Not Specified Metal Industries",
    "3MS": "MFG-Not Specified Manufacturing Industries",
    "4231": "WHL-Motor Vehicle And Motor Vehicle Parts And Supplies Merchant Wholesalers",
    "4232": "WHL-Furniture And Home Furnishing Merchant Wholesalers",
    "4233": "WHL-Lumber And Other Construction Materials Merchant Wholesalers",
    "4234": "WHL-Professional And Commercial Equipment And Supplies Merchant Wholesalers",
    "4235": "WHL-Metal And Mineral, Except Petroleum, Merchant Wholesalers",
    "4236": "WHL-Household Appliances And Electrical And Electronic Goods Merchant Wholesalers",
    "4237": "WHL-Hardware, And Plumbing And Heating Equipment, And Supplies Merchant Wholesalers",
    "4238": "WHL-Machinery, Equipment, And Supplies Merchant Wholesalers",
    "42393": "WHL-Recyclable Material Merchant Wholesalers",
    "4239Z": "WHL-Miscellaneous Durable Goods, Except Recyclable Material, Merchant Wholesalers",
    "4241": "WHL-Paper And Paper Product Merchant Wholesalers",
    "4243": "WHL-Apparel, Piece Goods, And Notions Merchant Wholesalers",
    "4244": "WHL-Grocery And Related Product Merchant Wholesalers",
    "4245": "WHL-Farm Product Raw Material Merchant Wholesalers",
    "4247": "WHL-Petroleum And Petroleum Products Merchant Wholesalers",
    "4248": "WHL-Beer, Wine, And Distilled Alcoholic Beverage Merchant Wholesalers",
    "42491": "WHL-Farm Supplies Merchant Wholesalers",
    "4249Z": "WHL-Miscellaneous Nondurable Goods Merchant, Except Farm Supplies, Wholesalers",
    "424M": "WHL-Drugs, Druggists' Sundries, And Chemical And Allied Products Merchant Wholesalers",
    "4251": "WHL-Wholesale Trade Agents And Brokers",
    "42S": "WHL-Not Specified Wholesale Trade",
    "4411": "RET-Automobile Dealers",
    "4412": "RET-Other Motor Vehicle Dealers",
    "4413": "RET-Automotive Parts, Accessories, And Tire Retailers",
    "44414": "RET-Hardware Retailers",
    "4441Z": "RET-Building Material And Supplies Dealers, Except Hardware Retailers",
    "4442": "RET-Lawn And Garden Equipment And Supplies Retailers",
    "44511": "RET-Supermarkets And Other Grocery (Except Convenience) Retailers",
    "44513": "RET-Convenience Retailers And Vending Machine Operators",
    "4452": "RET-Specialty Food Retailers",
    "4453": "RET-Beer, Wine, And Liquor Retailers",
    "4491": "RET-Furniture And Home Furnishings Retailers",
    "4492": "RET-Electronics And Appliance Retailers",
    "4551": "RET-Department Stores",
    "4552": "RET-Warehouse Clubs, Supercenters, And Other General Merchandise Retailers",
    "45611": "RET-Pharmacies And Drug Retailers",
    "4561Z": "RET-Health And Personal Care, Except Pharmacies And Drug, Retailers",
    "4571": "RET-Gasoline Stations",
    "4572": "RET-Fuel Dealers",
    "4581": "RET-Clothing And Clothing Accessories Retailers",
    "4582": "RET-Shoe Retailers",
    "4583": "RET-Jewelry, Luggage, And Leather Goods retailers",
    "45913": "RET-Sewing, Needlework, And Piece Goods Retailers",
    "45914": "RET-Musical Instrument And Supplies Retailers",
    "4591M": "RET-Sporting Goods, And Hobby, Toy, And Game Retailers",
    "45921": "RET-Book Retailers And News Dealers",
    "4593": "RET-Florists",
    "45941": "RET-Office Supplies And Stationery Retailers",
    "45942": "RET-Gift, Novelty, And Souvenir Retailers",
    "4595": "RET-Used Merchandise Retailers",
    "4599": "RET-Other Miscellaneous Retailers",
    "481": "TRN-Air Transportation",
    "482": "TRN-Rail Transportation",
    "483": "TRN-Water Transportation",
    "484": "TRN-Truck Transportation",
    "4853": "TRN-Taxi And Limousine Service",
    "485M": "TRN-Transit And Ground Passenger Transportation, Except Taxi And Limousine Service",
    "486": "TRN-Pipeline Transportation",
    "487": "TRN-Scenic And Sightseeing Transportation",
    "488": "TRN-Support Activities For Transportation",
    "491": "TRN-Postal Service",
    "492": "TRN-Couriers And Messengers",
    "493": "TRN-Warehousing And Storage",
    "4MS": "RET-Not Specified Retail Trade",
    "5121": "INF-Motion Pictures And Video Industries",
    "5122": "INF-Sound Recording Industries",
    "51311": "INF-Newspaper Publishers",
    "5131Z": "INF-Periodical, Book, And Directory And Mailing List, And Other Publishers",
    "5132": "INF-Software Publishers",
    "516": "INF-Broadcasting And Content Providers",
    "517111": "INF-Wired Telecommunications Carriers",
    "517Z": "INF-Telecommunications, Except Wired Telecommunications Carriers",
    "5182": "INF-Computing Infrastructure Providers, Data Processing, Web Hosting, And Related Services",
    "51921": "INF-Libraries And Archives",
    "51929": "INF-Web Search Portals And All Other Information Services",
    "5221M": "FIN-Credit Unions, And Savings Institutions And Other Depository Credit Intermediation",
    "522M": "FIN-Nondepository Credit Intermediation And Related Activities",
    "5241": "FIN-Insurance Carriers",
    "5242": "FIN-Agencies, Brokerages, And Other Insurance Related Activities",
    "52M2": "FIN-Securities, Commodities, Funds, Trusts, And Other Financial Investments",
    "52M3": "FIN-Monetary Authorities-Central Bank, And Commercial Banking",
    "5313": "FIN-Activities Related To Real Estate",
    "531M": "FIN-Lessors Of Real Estate, And Offices Of Real Estate Agents And Brokers",
    "5321": "FIN-Automotive Equipment Rental And Leasing",
    "532M2": "FIN-Consumer Goods Rental, And General Rental Centers",
    "53M": "FIN-Commercial And Industrial Machinery And Equipment, And Nonfinancial Intangible Assets Rental And Leasing",
    "5411": "PRF-Legal Services",
    "5412": "PRF-Accounting, Tax Preparation, Bookkeeping, And Payroll Services",
    "5413": "PRF-Architectural, Engineering, And Related Services",
    "5414": "PRF-Specialized Design Services",
    "5415": "PRF-Computer Systems Design And Related Services",
    "5416": "PRF-Management, Scientific, And Technical Consulting Services",
    "5417": "PRF-Scientific Research And Development Services",
    "5418": "PRF-Advertising, Public Relations, And Related Services",
    "54194": "PRF-Veterinary Services",
    "5419Z": "PRF-Other Professional, Scientific, And Technical, Except Veterinary, Services",
    "55": "PRF-Management Of Companies And Enterprises",
    "5613": "PRF-Employment Services",
    "5614": "PRF-Business Support Services",
    "5615": "PRF-Travel Arrangements And Reservation Services",
    "5616": "PRF-Investigation And Security Services",
    "56173": "PRF-Landscaping Services",
    "5617Z": "PRF-Services To Buildings And Dwellings, Except Landscaping Services",
    "561M": "PRF-Other Administrative And Other Support Services",
    "562": "PRF-Waste Management And Remediation Services",
    "6111": "EDU-Elementary And Secondary Schools",
    "611M1": "EDU-Junior Colleges, Colleges, Universities, And Professional Schools",
    "611M2": "EDU-Business, Trade And Technical Schools, And Computer And Management Training",
    "611M3": "EDU-Other Schools And Instruction, And Educational Support Services",
    "6211": "MED-Offices Of Physicians",
    "6212": "MED-Offices Of Dentists",
    "62131": "MED-Offices Of Chiropractors",
    "62132": "MED-Offices Of Optometrists",
    "6213ZM": "MED-Offices Of Other Health Practitioners",
    "6214": "MED-Outpatient Care Centers",
    "6216": "MED-Home Health Care Services",
    "621M": "MED-Other Health Care Services",
    "6222": "MED-Psychiatric And Substance Abuse Hospitals",
    "622M": "MED-General Medical And Surgical Hospitals, And Specialty (Except Psychiatric And Substance Abuse) Hospitals",
    "6231": "MED-Nursing Care Facilities (Skilled Nursing Facilities)",
    "623M": "MED-Residential Care Facilities, Except Skilled Nursing Facilities",
    "6241": "SCA-Individual And Family Services",
    "6242": "SCA-Community Food And Housing, And Emergency And Other Relief Services",
    "6243": "SCA-Vocational Rehabilitation Services",
    "6244": "SCA-Child Care Services",
    "7111": "ENT-Performing Arts Companies",
    "7112": "ENT-Spectator Sports",
    "7115": "ENT-Independent Artists, Writers, And Performers",
    "711M": "ENT-Promoters Of Performing Arts, Sports, And Similar Events, Agents And Managers For Artists, Athletes, Entertainers, And Other Public Figures",
    "712": "ENT-Museums, Historical Sites, And Similar Institutions",
    "71395": "ENT-Bowling Centers",
    "713Z": "ENT-Other Amusement, Gambling, And Recreation Industries",
    "7211": "ENT-Traveler Accommodation",
    "721M": "ENT-Recreational Vehicle Parks And Camps, And Rooming And Boarding Houses, Dormitories, And Workers' Camps",
    "7224": "ENT-Drinking Places (Alcoholic Beverages)",
    "722Z": "ENT-Food Services And Drinking Places, Except Alcoholic Beverages",
    "811192": "SRV-Car Washes",
    "8111Z": "SRV-Automotive Repair And Maintenance",
    "8112": "SRV-Electronic And Precision Equipment Repair And Maintenance",
    "8113": "SRV-Commercial And Industrial Machinery And Equipment Repair And Maintenance",
    "8114": "SRV-Personal And Household Goods Repair And Maintenance",
    "812111": "SRV-Barber Shops",
    "812112": "SRV-Beauty Salons",
    "8121M": "SRV-Nail Salons And Other Personal Care Services",
    "8122": "SRV-Death Care Services",
    "8123": "SRV-Drycleaning And Laundry Services",
    "8129": "SRV-Other Personal Services",
    "8131": "SRV-Religious Organizations",
    "81393": "SRV-Labor Unions And Similar Labor Organizations",
    "8139Z": "SRV-Business, Professional, Political, And Similar Organizations",
    "813M": "SRV-Civic, Social, Advocacy Organizations, And Grantmaking And Giving Services",
    "814": "SRV-Private Households",
    "92113": "ADM-Public Finance Activities",
    "92119": "ADM-Other General Government And Support",
    "9211MP": "ADM-Executive Offices And Legislative Bodies",
    "923": "ADM-Administration Of Human Resource Programs",
    "92811P1": "MIL-U.S. Army",
    "92811P2": "MIL-U.S. Air Force",
    "92811P3": "MIL-U.S. Navy",
    "92811P4": "MIL-U.S. Marines",
    "92811P5": "MIL-U.S. Coast Guard",
    "92811P6": "MIL-Armed Forces, Branch Not Specified",
    "92811P7": "MIL-Military Reserves Or National Guard",
    "9281P": "ADM-National Security And International Affairs",
    "92M1": "ADM-Administration Of Environmental Quality, And Housing Programs, Urban Planning And Community Development",
    "92M2": "ADM-Administration Of Economic Programs And Space Research And Technology",
    "92MP": "ADM-Justice, Public Order, And Safety Activities",
    "999920": "Unemployed, With No Work Experience In The Last 5 Years Or Earlier Or Never Worked",
    "N": "N/A (less than 16 years old/NILF who last worked more than 5 years ago or never worked)",
}

df['NAICSP 行业'] = df['NAICSP 行业'].astype(str)
df['NAICSP 行业'] = df['NAICSP 行业'].map(naics_dict).fillna('NA')

socp_dict = {
    "111021": "MGR-General And Operations Managers",
    "1110XX": "MGR-Chief Executives And Legislators",
    "112011": "MGR-Advertising And Promotions Managers",
    "112021": "MGR-Marketing Managers",
    "112022": "MGR-Sales Managers",
    "112030": "MGR-Public Relations And Fundraising Managers",
    "113012": "MGR-Administrative Services Managers",
    "113013": "MGR-Facilities Managers",
    "113021": "MGR-Computer And Information Systems Managers",
    "113031": "MGR-Financial Managers",
    "113051": "MGR-Industrial Production Managers",
    "113061": "MGR-Purchasing Managers",
    "113071": "MGR-Transportation, Storage, And Distribution Managers",
    "113111": "MGR-Compensation And Benefits Managers",
    "113121": "MGR-Human Resources Managers",
    "113131": "MGR-Training And Development Managers",
    "119013": "MGR-Farmers, Ranchers, And Other Agricultural Managers",
    "119021": "MGR-Construction Managers",
    "119030": "MGR-Education And Childcare Administrators",
    "119041": "MGR-Architectural And Engineering Managers",
    "119051": "MGR-Food Service Managers",
    "119070": "MGR-Entertainment And Recreation Managers",
    "119081": "MGR-Lodging Managers",
    "119111": "MGR-Medical And Health Services Managers",
    "119121": "MGR-Natural Sciences Managers",
    "119141": "MGR-Property, Real Estate, And Community Association Managers",
    "119151": "MGR-Social And Community Service Managers",
    "119161": "MGR-Emergency Management Directors",
    "1191XX": "MGR-Other Managers",
    "131011": "BUS-Agents And Business Managers Of Artists, Performers, And Athletes",
    "131021": "BUS-Buyers And Purchasing Agents, Farm Products",
    "131022": "BUS-Wholesale And Retail Buyers, Except Farm Products",
    "131023": "BUS-Purchasing Agents, Except Wholesale, Retail, And Farm Products",
    "131030": "BUS-Claims Adjusters, Appraisers, Examiners, And Investigators",
    "131041": "BUS-Compliance Officers",
    "131051": "BUS-Cost Estimators",
    "131070": "BUS-Human Resources Workers",
    "131081": "BUS-Logisticians",
    "131082": "BUS-Project Management Specialists",
    "131111": "BUS-Management Analysts",
    "131121": "BUS-Meeting, Convention, And Event Planners",
    "131131": "BUS-Fundraisers",
    "131141": "BUS-Compensation, Benefits, And Job Analysis Specialists",
    "131151": "BUS-Training And Development Specialists",
    "131161": "BUS-Market Research Analysts And Marketing Specialists",
    "131199": "BUS-Business Operations Specialists, All Other",
    "132011": "FIN-Accountants And Auditors",
    "132020": "FIN-Property Appraisers And Assessors",
    "132031": "FIN-Budget Analysts",
    "132041": "FIN-Credit Analysts",
    "132051": "FIN-Financial And Investment Analysts",
    "132052": "FIN-Personal Financial Advisors",
    "132053": "FIN-Insurance Underwriters",
    "132061": "FIN-Financial Examiners",
    "132070": "FIN-Credit Counselors And Loan Officers",
    "132081": "FIN-Tax Examiners And Collectors, And Revenue Agents",
    "132082": "FIN-Tax Preparers",
    "1320XX": "FIN-Other Financial Specialists",
    "151211": "CMM-Computer Systems Analysts",
    "151212": "CMM-Information Security Analysts",
    "151221": "CMM-Computer And Information Research Scientists",
    "151230": "CMM-Computer Support Specialists",
    "151241": "CMM-Computer Network Architects",
    "151244": "CMM-Network And Computer Systems Administrators",
    "15124X": "CMM-Database Administrators And Architects",
    "151251": "CMM-Computer Programmers",
    "151252": "CMM-Software Developers",
    "151253": "CMM-Software Quality Assurance Analysts And Testers",
    "151254": "CMM-Web Developers",
    "151255": "CMM-Web And Digital Interface Designers",
    "151299": "CMM-Computer Occupations, All Other",
    "152011": "CMM-Actuaries",
    "152031": "CMM-Operations Research Analysts",
    "1520XX": "CMM-Other Mathematical Science Occupations",
    "171011": "ENG-Architects, Except Landscape And Naval",
    "171012": "ENG-Landscape Architects",
    "171020": "ENG-Surveyors, Cartographers, And Photogrammetrists",
    "172011": "ENG-Aerospace Engineers",
    "172041": "ENG-Chemical Engineers",
    "172051": "ENG-Civil Engineers",
    "172061": "ENG-Computer Hardware Engineers",
    "172070": "ENG-Electrical And Electronics Engineers",
    "172081": "ENG-Environmental Engineers",
    "1720XX": "ENG-Biomedical And Agricultural Engineers",
    "172110": "ENG-Industrial Engineers, Including Health And Safety",
    "172121": "ENG-Marine Engineers And Naval Architects",
    "172131": "ENG-Materials Engineers",
    "172141": "ENG-Mechanical Engineers",
    "1721XX": "ENG-Petroleum, Mining And Geological Engineers, Including Mining Safety Engineers",
    "1721YY": "ENG-Other Engineers",
    "173011": "ENG-Architectural And Civil Drafters",
    "17301X": "ENG-Other Drafters",
    "173023": "ENG-Electrical and Electronic Engineering Technologists And Technicians",
    "17302X": "ENG-Other Engineering Technologists And Technicians, Except Drafters",
    "173031": "ENG-Surveying And Mapping Technicians",
    "191010": "SCI-Agricultural And Food Scientists",
    "191020": "SCI-Biological Scientists",
    "191030": "SCI-Conservation Scientists And Foresters",
    "1910XX": "SCI-Other Life Scientists",
    "192010": "SCI-Astronomers And Physicists",
    "192021": "SCI-Atmospheric And Space Scientists",
    "192030": "SCI-Chemists And Materials Scientists",
    "192041": "SCI-Environmental Scientists And Specialists, Including Health",
    "19204X": "SCI-Geoscientists And Hydrologists, Except Geographers",
    "192099": "SCI-Physical Scientists, All Other",
    "193011": "SCI-Economists",
    "193033": "SCI-Clinical And Counseling Psychologists",
    "193034": "SCI-School Psychologists",
    "19303X": "SCI-Other Psychologists",
    "193051": "SCI-Urban And Regional Planners",
    "1930XX": "SCI-Other Social Scientists",
    "194010": "SCI-Agricultural And Food Science Technicians",
    "194021": "SCI-Biological Technicians",
    "194031": "SCI-Chemical Technicians",
    "1940XX": "SCI-Environmental Science And Geoscience Technicians, And Nuclear Technicians",
    "1940YY": "SCI-Other Life, Physical, And Social Science Technicians",
    "195010": "SCI-Occupational Health And Safety Specialists And Technicians",
    "211011": "CMS-Substance Abuse And Behavioral Disorder Counselors",
    "211012": "CMS-Educational, Guidance, And Career Counselors And Advisors",
    "211013": "CMS-Marriage And Family Therapists",
    "211014": "CMS-Mental Health Counselors",
    "211015": "CMS-Rehabilitation Counselors",
    "211019": "CMS-Counselors, All Other",
    "211021": "CMS-Child, Family, And School Social Workers",
    "211022": "CMS-Healthcare Social Workers",
    "211023": "CMS-Mental Health And Substance Abuse Social Workers",
    "211029": "CMS-Social Workers, All Other",
    "211092": "CMS-Probation Officers And Correctional Treatment Specialists",
    "211093": "CMS-Social And Human Service Assistants",
    "21109X": "CMS-Other Community And Social Service Specialists",
    "212011": "CMS-Clergy",
    "212021": "CMS-Directors, Religious Activities And Education",
    "212099": "CMS-Religious Workers, All Other",
    "231012": "LGL-Judicial Law Clerks",
    "2310XX": "LGL-Lawyers, And Judges, Magistrates, And Other Judicial Workers",
    "232011": "LGL-Paralegals And Legal Assistants",
    "232093": "LGL-Title Examiners, Abstractors, And Searchers",
    "232099": "LGL-Legal Support Workers, All Other",
    "251000": "EDU-Postsecondary Teachers",
    "252010": "EDU-Preschool And Kindergarten Teachers",
    "252020": "EDU-Elementary And Middle School Teachers",
    "252030": "EDU-Secondary School Teachers",
    "252050": "EDU-Special Education Teachers",
    "253041": "EDU-Tutors",
    "2530XX": "EDU-Other Teachers And Instructors",
    "254010": "EDU-Archivists, Curators, And Museum Technicians",
    "254022": "EDU-Librarians And Media Collections Specialists",
    "254031": "EDU-Library Technicians",
    "259040": "EDU-Teaching Assistants",
    "2590XX": "EDU-Other Educational Instruction and Library Workers",
    "271010": "ENT-Artists And Related Workers",
    "271021": "ENT-Commercial And Industrial Designers",
    "271022": "ENT-Fashion Designers",
    "271023": "ENT-Floral Designers",
    "271024": "ENT-Graphic Designers",
    "271025": "ENT-Interior Designers",
    "271026": "ENT-Merchandise Displayers And Window Trimmers",
    "27102X": "ENT-Other Designers",
    "272011": "ENT-Actors",
    "272012": "ENT-Producers And Directors",
    "272021": "ENT-Athletes And Sports Competitors",
    "272022": "ENT-Coaches And Scouts",
    "272023": "ENT-Umpires, Referees, And Other Sports Officials",
    "272030": "ENT-Dancers And Choreographers",
    "272041": "ENT-Music Directors And Composers",
    "272042": "ENT-Musicians And Singers",
    "272091": "ENT-Disc Jockeys, Except Radio",
    "272099": "ENT-Entertainers And Performers, Sports And Related Workers, All Other",
    "273011": "ENT-Broadcast Announcers And Radio Disc Jockeys",
    "273023": "ENT-News Analysts, Reporters, And Journalists",
    "273031": "ENT-Public Relations Specialists",
    "273041": "ENT-Editors",
    "273042": "ENT-Technical Writers",
    "273043": "ENT-Writers And Authors",
    "273091": "ENT-Interpreters And Translators",
    "273092": "ENT-Court Reporters And Simultaneous Captioners",
    "273099": "ENT-Media And Communication Workers, All Other",
    "274021": "ENT-Photographers",
    "274030": "ENT-Television, Video, And Film Camera Operators And Editors",
    "2740XX": "ENT-Other Media And Communication Equipment Workers",
    "291011": "MED-Chiropractors",
    "291020": "MED-Dentists",
    "291031": "MED-Dietitians And Nutritionists",
    "291041": "MED-Optometrists",
    "291051": "MED-Pharmacists",
    "291071": "MED-Physician Assistants",
    "291081": "MED-Podiatrists",
    "291122": "MED-Occupational Therapists",
    "291123": "MED-Physical Therapists",
    "291124": "MED-Radiation Therapists",
    "291125": "MED-Recreational Therapists",
    "291126": "MED-Respiratory Therapists",
    "291127": "MED-Speech-Language Pathologists",
    "29112X": "MED-Other Therapists",
    "291131": "MED-Veterinarians",
    "291141": "MED-Registered Nurses",
    "291151": "MED-Nurse Anesthetists",
    "291181": "MED-Audiologists",
    "2911XX": "MED-Nurse Practitioners, And Nurse Midwives",
    "291210": "MED-Physicians",
    "291240": "MED-Surgeons",
    "291291": "MED-Acupuncturists",
    "291292": "MED-Dental Hygienists",
    "291299": "MED-Healthcare Diagnosing Or Treating Practitioners, All Other",
    "292010": "MED-Clinical Laboratory Technologists And Technicians",
    "292031": "MED-Cardiovascular Technologists And Technicians",
    "292032": "MED-Diagnostic Medical Sonographers",
    "292034": "MED-Radiologic Technologists And Technicians",
    "292035": "MED-Magnetic Resonance Imaging Technologists",
    "29203X": "MED-Nuclear Medicine Technologists And Medical Dosimetrists",
    "292042": "MED-Emergency Medical Technicians",
    "292043": "MED-Paramedics",
    "292052": "MED-Pharmacy Technicians",
    "292053": "MED-Psychiatric Technicians",
    "292055": "MED-Surgical Technologists",
    "292056": "MED-Veterinary Technologists And Technicians",
    "29205X": "MED-Dietetic Technicians And Ophthalmic Medical Technicians",
    "292061": "MED-Licensed Practical And Licensed Vocational Nurses",
    "292072": "MED-Medical Records Specialists",
    "292081": "MED-Opticians, Dispensing",
    "292090": "MED-Miscellaneous Health Technologists And Technicians",
    "299000": "MED-Other Healthcare Practitioners And Technical Occupations",
    "311121": "HLS-Home Health Aides",
    "311122": "HLS-Personal Care Aides",
    "311131": "HLS-Nursing Assistants",
    "31113X": "HLS-Orderlies And Psychiatric Aides",
    "312010": "HLS-Occupational Therapy Assistants And Aides",
    "312020": "HLS-Physical Therapist Assistants And Aides",
    "319011": "HLS-Massage Therapists",
    "319091": "HLS-Dental Assistants",
    "319092": "HLS-Medical Assistants",
    "319094": "HLS-Medical Transcriptionists",
    "319095": "HLS-Pharmacy Aides",
    "319096": "HLS-Veterinary Assistants And Laboratory Animal Caretakers",
    "319097": "HLS-Phlebotomists",
    "31909X": "HLS-Other Healthcare Support Workers",
    "331011": "PRT-First-Line Supervisors Of Correctional Officers",
    "331012": "PRT-First-Line Supervisors Of Police And Detectives",
    "331021": "PRT-First-Line Supervisors Of Firefighting And Prevention Workers",
    "331090": "PRT-Miscellaneous First-Line Supervisors, Protective Service Workers",
    "332011": "PRT-Firefighters",
    "332020": "PRT-Fire Inspectors",
    "333011": "PRT-Bailiffs",
    "333012": "PRT-Correctional Officers And Jailers",
    "333021": "PRT-Detectives And Criminal Investigators",
    "333050": "PRT-Police Officers",
    "3330XX": "PRT-Fish And Game Wardens And Parking Enforcement Officers",
    "339011": "PRT-Animal Control Workers",
    "339021": "PRT-Private Detectives And Investigators",
    "339030": "PRT-Security Guards And Gambling Surveillance Officers",
    "339091": "PRT-Crossing Guards And Flaggers",
    "339093": "PRT-Transportation Security Screeners",
    "339094": "PRT-School Bus Monitors",
    "33909X": "PRT-Other Protective Service Workers",
    "351011": "EAT-Chefs And Head Cooks",
    "351012": "EAT-First-Line Supervisors Of Food Preparation And Serving Workers",
    "352010": "EAT-Cooks",
    "352021": "EAT-Food Preparation Workers",
    "353011": "EAT-Bartenders",
    "353023": "EAT-Fast Food And Counter Workers",
    "353031": "EAT-Waiters And Waitresses",
    "353041": "EAT-Food Servers, Nonrestaurant",
    "359011": "EAT-Dining Room And Cafeteria Attendants And Bartender Helpers",
    "359021": "EAT-Dishwashers",
    "359031": "EAT-Hosts And Hostesses, Restaurant, Lounge, And Coffee Shop",
    "359099": "EAT-Food Preparation And Serving Related Workers, All Other",
    "371011": "CLN-First-Line Supervisors Of Housekeeping And Janitorial Workers",
    "371012": "CLN-First-Line Supervisors Of Landscaping, Lawn Service, And Groundskeeping Workers",
    "372012": "CLN-Maids And Housekeeping Cleaners",
    "37201X": "CLN-Janitors And Building Cleaners",
    "372021": "CLN-Pest Control Workers",
    "373011": "CLN-Landscaping And Groundskeeping Workers",
    "373013": "CLN-Tree Trimmers And Pruners",
    "37301X": "CLN-Other Grounds Maintenance Workers",
    "391000": "PRS-Supervisors of Personal Care And Service Workers",
    "392011": "PRS-Animal Trainers",
    "392021": "PRS-Animal Caretakers",
    "393010": "PRS-Gambling Services Workers",
    "393031": "PRS-Ushers, Lobby Attendants, And Ticket Takers",
    "3930XX": "PRS-Other Entertainment Attendants And Related Workers",
    "394031": "PRS-Morticians, Undertakers, And Funeral Arrangers",
    "3940XX": "PRS-Embalmers, Crematory Operators And Funeral Attendants",
    "395011": "PRS-Barbers",
    "395012": "PRS-Hairdressers, Hairstylists, And Cosmetologists",
    "395092": "PRS-Manicurists and Pedicurists",
    "395094": "PRS-Skincare Specialists",
    "39509X": "PRS-Other Personal Appearance Workers",
    "396010": "PRS-Baggage Porters, Bellhops, And Concierges",
    "397010": "PRS-Tour And Travel Guides",
    "399011": "PRS-Childcare Workers",
    "399031": "PRS-Exercise Trainers And Group Fitness Instructors",
    "399032": "PRS-Recreation Workers",
    "399041": "PRS-Residential Advisors",
    "399099": "PRS-Personal Care And Service Workers, All Other",
    "411011": "SAL-First-Line Supervisors Of Retail Sales Workers",
    "411012": "SAL-First-Line Supervisors Of Non-Retail Sales Workers",
    "412010": "SAL-Cashiers",
    "412021": "SAL-Counter And Rental Clerks",
    "412022": "SAL-Parts Salespersons",
    "412031": "SAL-Retail Salespersons",
    "413011": "SAL-Advertising Sales Agents",
    "413021": "SAL-Insurance Sales Agents",
    "413031": "SAL-Securities, Commodities, And Financial Services Sales Agents",
    "413041": "SAL-Travel Agents",
    "413091": "SAL-Sales Representatives Of Services, Except Advertising, Insurance, Financial Services, And Travel",
    "414010": "SAL-Sales Representatives, Wholesale And Manufacturing",
    "419010": "SAL-Models, Demonstrators, And Product Promoters",
    "419020": "SAL-Real Estate Brokers And Sales Agents",
    "419031": "SAL-Sales Engineers",
    "419041": "SAL-Telemarketers",
    "419091": "SAL-Door-To-Door Sales Workers, News And Street Vendors, And Related Workers",
    "419099": "SAL-Sales And Related Workers, All Other",
    "431011": "OFF-First-Line Supervisors Of Office And Administrative Support Workers",
    "432011": "OFF-Switchboard Operators, Including Answering Service",
    "432021": "OFF-Telephone Operators",
    "432099": "OFF-Communications Equipment Operators, All Other",
    "433011": "OFF-Bill And Account Collectors",
    "433021": "OFF-Billing And Posting Clerks",
    "433031": "OFF-Bookkeeping, Accounting, And Auditing Clerks",
    "433051": "OFF-Payroll And Timekeeping Clerks",
    "433061": "OFF-Procurement Clerks",
    "433071": "OFF-Tellers",
    "4330XX": "OFF-Other Financial Clerks",
    "434031": "OFF-Court, Municipal, And License Clerks",
    "434041": "OFF-Credit Authorizers, Checkers, And Clerks",
    "434051": "OFF-Customer Service Representatives",
    "434061": "OFF-Eligibility Interviewers, Government Programs",
    "434071": "OFF-File Clerks",
    "434081": "OFF-Hotel, Motel, And Resort Desk Clerks",
    "434111": "OFF-Interviewers, Except Eligibility And Loan",
    "434121": "OFF-Library Assistants, Clerical",
    "434131": "OFF-Loan Interviewers And Clerks",
    "434141": "OFF-New Accounts Clerks",
    "434161": "OFF-Human Resources Assistants, Except Payroll And Timekeeping",
    "434171": "OFF-Receptionists And Information Clerks",
    "434181": "OFF-Reservation And Transportation Ticket Agents And Travel Clerks",
    "434XXX": "OFF-Correspondence Clerks And Order Clerks",
    "434YYY": "OFF-Other Information And Records Clerks",
    "435011": "OFF-Cargo And Freight Agents",
    "435021": "OFF-Couriers And Messengers",
    "435031": "OFF-Public Safety Telecommunicators",
    "435032": "OFF-Dispatchers, Except Police, Fire, And Ambulance",
    "435041": "OFF-Meter Readers, Utilities",
    "435051": "OFF-Postal Service Clerks",
    "435052": "OFF-Postal Service Mail Carriers",
    "435053": "OFF-Postal Service Mail Sorters, Processors, And Processing Machine Operators",
    "435061": "OFF-Production, Planning, And Expediting Clerks",
    "435071": "OFF-Shipping, Receiving, And Inventory Clerks",
    "435111": "OFF-Weighers, Measurers, Checkers, And Samplers, Recordkeeping",
    "436011": "OFF-Executive Secretaries And Executive Administrative Assistants",
    "436012": "OFF-Legal Secretaries And Administrative Assistants",
    "436013": "OFF-Medical Secretaries And Administrative Assistants",
    "436014": "OFF-Secretaries And Administrative Assistants, Except Legal, Medical, And Executive",
    "439021": "OFF-Data Entry Keyers",
    "439022": "OFF-Word Processors And Typists",
    "439041": "OFF-Insurance Claims And Policy Processing Clerks",
    "439051": "OFF-Mail Clerks And Mail Machine Operators, Except Postal Service",
    "439061": "OFF-Office Clerks, General",
    "439071": "OFF-Office Machine Operators, Except Computer",
    "439081": "OFF-Proofreaders And Copy Markers",
    "439111": "OFF-Statistical Assistants",
    "439XXX": "OFF-Other Office And Administrative Support Workers",
    "451011": "FFF-First-Line Supervisors Of Farming, Fishing, And Forestry Workers",
    "452011": "FFF-Agricultural Inspectors",
    "452041": "FFF-Graders And Sorters, Agricultural Products",
    "4520XX": "FFF-Other Agricultural Workers",
    "453031": "FFF-Fishing And Hunting Workers",
    "454011": "FFF-Forest And Conservation Workers",
    "454020": "FFF-Logging Workers",
    "471011": "CON-First-Line Supervisors Of Construction Trades And Extraction Workers",
    "472011": "CON-Boilermakers",
    "472031": "CON-Carpenters",
    "472040": "CON-Carpet, Floor, And Tile Installers And Finishers",
    "472050": "CON-Cement Masons, Concrete Finishers, And Terrazzo Workers",
    "472061": "CON-Construction Laborers",
    "472070": "CON-Construction Equipment Operators",
    "472080": "CON-Drywall Installers, Ceiling Tile Installers, And Tapers",
    "472111": "CON-Electricians",
    "472121": "CON-Glaziers",
    "472130": "CON-Insulation Workers",
    "472140": "CON-Painters And Paperhangers",
    "472151": "CON-Pipelayers",
    "472152": "CON-Plumbers, Pipefitters, And Steamfitters",
    "472161": "CON-Plasterers And Stucco Masons",
    "472181": "CON-Roofers",
    "472211": "CON-Sheet Metal Workers",
    "472221": "CON-Structural Iron And Steel Workers",
    "472231": "CON-Solar Photovoltaic Installers",
    "472XXX": "CON-Brickmasons, Blockmasons, Stonemasons, And Reinforcing Iron And Rebar Workers",
    "473010": "CON-Helpers, Construction Trades",
    "474011": "CON-Construction And Building Inspectors",
    "474021": "CON-Elevator And Escalator Installers And Repairers",
    "474031": "CON-Fence Erectors",
    "474041": "CON-Hazardous Materials Removal Workers",
    "474051": "CON-Highway Maintenance Workers",
    "474061": "CON-Rail-Track Laying And Maintenance Equipment Operators",
    "4740XX": "CON-Other Construction And Related Workers",
    "475020": "EXT-Surface Mining Machine Operators And Earth Drillers",
    "475032": "EXT-Explosives Workers, Ordnance Handling Experts, And Blasters",
    "475040": "EXT-Underground Mining Machine Operators",
    "4750XX": "EXT-Other Extraction Workers",
    "4750YY": "EXT-Derrick, Rotary Drill, And Service Unit Operators, And Roustabouts, Oil And Gas",
    "491011": "RPR-First-Line Supervisors Of Mechanics, Installers, And Repairers",
    "492011": "RPR-Computer, Automated Teller, And Office Machine Repairers",
    "492020": "RPR-Radio And Telecommunications Equipment Installers And Repairers",
    "492091": "RPR-Avionics Technicians",
    "492092": "RPR-Electric Motor, Power Tool, And Related Repairers",
    "492097": "RPR-Audiovisual Equipment Installers And Repairers",
    "492098": "RPR-Security And Fire Alarm Systems Installers",
    "49209X": "RPR-Other Electrical And Electronic Equipment Mechanics, Installers, and Repairers",
    "493011": "RPR-Aircraft Mechanics And Service Technicians",
    "493021": "RPR-Automotive Body And Related Repairers",
    "493022": "RPR-Automotive Glass Installers And Repairers",
    "493023": "RPR-Automotive Service Technicians And Mechanics",
    "493031": "RPR-Bus And Truck Mechanics And Diesel Engine Specialists",
    "493040": "RPR-Heavy Vehicle And Mobile Equipment Service Technicians And Mechanics",
    "493050": "RPR-Small Engine Mechanics",
    "493090": "RPR-Miscellaneous Vehicle And Mobile Equipment Mechanics, Installers, And Repairers",
    "499010": "RPR-Control And Valve Installers And Repairers",
    "499021": "RPR-Heating, Air Conditioning, And Refrigeration Mechanics And Installers",
    "499031": "RPR-Home Appliance Repairers",
    "499043": "RPR-Maintenance Workers, Machinery",
    "499044": "RPR-Millwrights",
    "49904X": "RPR-Industrial And Refractory Machinery Mechanics",
    "499051": "RPR-Electrical Power-Line Installers And Repairers",
    "499052": "RPR-Telecommunications Line Installers And Repairers",
    "499060": "RPR-Precision Instrument And Equipment Repairers",
    "499071": "RPR-Maintenance And Repair Workers, General",
    "499091": "RPR-Coin, Vending, And Amusement Machine Servicers And Repairers",
    "499094": "RPR-Locksmiths And Safe Repairers",
    "499096": "RPR-Riggers",
    "499098": "RPR-Helpers--Installation, Maintenance, And Repair Workers",
    "4990XX": "RPR-Other Installation, Maintenance, And Repair Workers",
    "511011": "PRD-First-Line Supervisors Of Production And Operating Workers",
    "512020": "PRD-Electrical, Electronics, And Electromechanical Assemblers",
    "512031": "PRD-Engine And Other Machine Assemblers",
    "512041": "PRD-Structural Metal Fabricators And Fitters",
    "5120XX": "PRD-Other Assemblers and Fabricators",
    "513011": "PRD-Bakers",
    "513020": "PRD-Butchers And Other Meat, Poultry, And Fish Processing Workers",
    "513091": "PRD-Food And Tobacco Roasting, Baking, And Drying Machine Operators And Tenders",
    "513092": "PRD-Food Batchmakers",
    "513093": "PRD-Food Cooking Machine Operators And Tenders",
    "513099": "PRD-Food Processing Workers, All Other",
    "514020": "PRD-Forming Machine Setters, Operators, And Tenders, Metal And Plastic",
    "514031": "PRD-Cutting, Punching, And Press Machine Setters, Operators, And Tenders, Metal And Plastic",
    "514033": "PRD-Grinding, Lapping, Polishing, And Buffing Machine Tool Setters, Operators, And Tenders, Metal and Plastic",
    "51403X": "PRD-Other Machine Tool Setters, Operators, And Tenders, Metal And Plastic",
    "514041": "PRD-Machinists",
    "514050": "PRD-Metal Furnace Operators, Tenders, Pourers, And Casters",
    "5140XX": "PRD-Model Makers, Patternmakers, And Molding Machine Setters, Metal And Plastic",
    "514111": "PRD-Tool And Die Makers",
    "514120": "PRD-Welding, Soldering, And Brazing Workers",
    "514XXX": "PRD-Other Metal Workers And Plastic Workers",
    "515111": "PRD-Prepress Technicians And Workers",
    "515112": "PRD-Printing Press Operators",
    "515113": "PRD-Print Binding And Finishing Workers",
    "516011": "PRD-Laundry And Dry-Cleaning Workers",
    "516021": "PRD-Pressers, Textile, Garment, And Related Materials",
    "516031": "PRD-Sewing Machine Operators",
    "516040": "PRD-Shoe And Leather Workers",
    "516050": "PRD-Tailors, Dressmakers, And Sewers",
    "516060": "PRD-Textile Machine Setters, Operators, And Tenders",
    "516093": "PRD-Upholsterers",
    "51609X": "PRD-Other Textile, Apparel, And Furnishings Workers",
    "517011": "PRD-Cabinetmakers And Bench Carpenters",
    "517021": "PRD-Furniture Finishers",
    "517041": "PRD-Sawing Machine Setters, Operators, And Tenders, Wood",
    "517042": "PRD-Woodworking Machine Setters, Operators, And Tenders, Except Sawing",
    "5170XX": "PRD-Other Woodworkers",
    "518010": "PRD-Power Plant Operators, Distributors, And Dispatchers",
    "518021": "PRD-Stationary Engineers And Boiler Operators",
    "518031": "PRD-Water And Wastewater Treatment Plant And System Operators",
    "518090": "PRD-Miscellaneous Plant And System Operators",
    "519010": "PRD-Chemical Processing Machine Setters, Operators, And Tenders",
    "519020": "PRD-Crushing, Grinding, Polishing, Mixing, And Blending Workers",
    "519030": "PRD-Cutting Workers",
    "519041": "PRD-Extruding, Forming, Pressing, And Compacting Machine Setters, Operators, And Tenders",
    "519051": "PRD-Furnace, Kiln, Oven, Drier, And Kettle Operators And Tenders",
    "519061": "PRD-Inspectors, Testers, Sorters, Samplers, And Weighers",
    "519071": "PRD-Jewelers And Precious Stone And Metal Workers",
    "519080": "PRD-Dental And Ophthalmic Laboratory Technicians And Medical Appliance Technicians",
    "519111": "PRD-Packaging And Filling Machine Operators And Tenders",
    "519120": "PRD-Painting Workers",
    "519151": "PRD-Photographic Process Workers And Processing Machine Operators",
    "519160": "PRD-Computer Numerically Controlled Tool Operators And Programmers",
    "519191": "PRD-Adhesive Bonding Machine Operators And Tenders",
    "519194": "PRD-Etchers And Engravers",
    "519195": "PRD-Molders, Shapers, And Casters, Except Metal And Plastic",
    "519196": "PRD-Paper Goods Machine Setters, Operators, And Tenders",
    "519197": "PRD-Tire Builders",
    "519198": "PRD-Helpers--Production Workers",
    "5191XX": "PRD-Miscellaneous Production Workers, Including Equipment Operators and Tenders",
    "531000": "TRN-Supervisors Of Transportation And Material Moving Workers",
    "532010": "TRN-Aircraft Pilots And Flight Engineers",
    "532020": "TRN-Air Traffic Controllers And Airfield Operations Specialists",
    "532031": "TRN-Flight Attendants",
    "533011": "TRN-Ambulance Drivers And Attendants, Except Emergency Medical Technicians",
    "533030": "TRN-Driver/Sales Workers And Truck Drivers",
    "533051": "TRN-Bus Drivers, School",
    "533052": "TRN-Bus Drivers, Transit And Intercity",
    "533053": "TRN-Shuttle Drivers and Chauffeurs",
    "533054": "TRN-Taxi Drivers",
    "533099": "TRN-Motor Vehicle Operators, All Other",
    "534010": "TRN-Locomotive Engineers And Operators",
    "534031": "TRN-Railroad Conductors And Yardmasters",
    "5340XX": "TRN-Other Rail Transportation Workers",
    "535020": "TRN-Ship And Boat Captains And Operators",
    "5350XX": "TRN-Sailors And Marine Oilers, And Ship Engineers",
    "536021": "TRN-Parking Attendants",
    "536030": "TRN-Transportation Service Attendants",
    "536051": "TRN-Transportation Inspectors",
    "536061": "TRN-Passenger Attendants",
    "5360XX": "TRN-Other Transportation Workers",
    "537021": "TRN-Crane And Tower Operators",
    "537051": "TRN-Industrial Truck And Tractor Operators",
    "537061": "TRN-Cleaners Of Vehicles And Equipment",
    "537062": "TRN-Laborers And Freight, Stock, And Material Movers, Hand",
    "537063": "TRN-Machine Feeders And Offbearers",
    "537064": "TRN-Packers And Packagers, Hand",
    "537065": "TRN-Stockers And Order Fillers",
    "537070": "TRN-Pumping Station Operators",
    "537081": "TRN-Refuse And Recyclable Material Collectors",
    "5370XX": "TRN-Conveyor, Dredge, And Hoist And Winch Operators",
    "5371XX": "TRN-Other Material Moving Workers",
    "551010": "MIL-Military Officer Special And Tactical Operations Leaders",
    "552010": "MIL-First-Line Enlisted Military Supervisors",
    "553010": "MIL-Military Enlisted Tactical Operations And Air/Weapons Specialists And Crew Members",
    "559830": "MIL-Military, Rank Not Specified",
    "999920": "Unemployed, With No Work Experience In The Last 5 Years Or Earlier Or Never Worked",
    "N": "N/A (less than 16 years old/NILF who last worked more than 5 years ago or never worked)"
}

df['SOCP 职位'] = df['SOCP 职位'].astype(str)
df['SOCP 职位'] = df['SOCP 职位'].map(socp_dict).fillna('NA')


df.to_csv("pure_sampled_data.csv", index=False, encoding='utf-8-sig')